# file: postgresql/tasks/users_privileges.yml

- name: PostgreSQL | Update the user privileges
  postgresql_user:
    name: "{{item.name}}"
    db: "{{item.db | default(omit)}}"
    port: "{{postgresql_port}}"
    priv: "{{item.priv | default(omit)}}"
    state: present
    login_host: "{{item.host | default(omit)}}"
    login_user: "{{postgresql_admin_user}}"
    role_attr_flags: "{{item.role_attr_flags | default(omit)}}"
  become: yes
  become_user: "{{postgresql_admin_user}}"
  with_items: "{{postgresql_user_privileges}}"
  when: postgresql_users|length > 0


- name: PostgreSQL | Update the database privileges
  postgresql_privs:
    db: "{{item.db | default(omit)}}"
    privs: "{{item.privs | default(omit)}}"
    role: "{{item.role | default(omit)}}"
    type: "{{item.type | default(omit)}}"
    obj: "{{item.obj | default(omit)}}"
  become: yes
  become_user: "{{postgresql_admin_user}}"
  with_items: "{{postgresql_database_privileges}}"
  when: postgresql_database_privileges|length > 0