---

apache_http_port: 80
apache_https_port: 443

apache_listen_directives: |
  Listen {{ apache_http_port }}

  <IfModule ssl_module>
    Listen {{ apache_https_port }}
  </IfModule>

  <IfModule mod_gnutls.c>
    Listen {{ apache_https_port }}
  </IfModule>

apache_create_vhosts: true
apache_vhosts_filename: "vhosts.conf"

# On Debian/Ubuntu, a default virtualhost is included in Apache's configuration.
# Set this to `true` to remove that default; otherwise `false`.
apache_remove_default_vhost: true

apache_vhosts:
  # Additional properties: `serveradmin`, `serveralias`, `usecanonicalname`, 
  # `extra_parameters`.
  - servername: "{{ inventory_hostname }}"
    documentroot: "/var/www/html"
    directory:
      - "/var/www/html"
      - "/var/www/html/registry"
    registry_auth:
      - path: "/var/www/html/registry/auth/login"
      - path: "/var/www/html/registry/auth/logout"
        redirect_host: "{{ inventory_hostname }}"

apache_vhosts_ssl: []
  # Additional properties: `serveradmin`, `serveralias`, `usecanonicalname`,
  # `extra_parameters`.
  # - servername: "www.example.com"
  #   documentroot: "/var/www/html"
  #   certificate_file: "/path/to/certificate.crt"
  #   certificate_key_file: "/path/to/certificate.key"
  #   # Optional.
  #   certificate_chain_file: "/path/to/certificate_chain.crt"

apache_ignore_missing_ssl_certificate: true

#apache_ssl_protocol: "All -SSLv2 -SSLv3"
#apache_ssl_cipher_suite: "AES256+EECDH:AES256+EDH"

# Initial apache state, i.e. `started`, `stopped`, `restarted`, or `reloaded`
apache_state: "started"

# Only used on Debian/Ubuntu.
apache_mods_enabled:
  - ssl
  - rewrite
  - php5.load # add *.load after the module if it is installed manually
apache_mods_disabled: []
