---

- import_playbook: cacheservers.yml

- import_playbook: authservers.yml

- include: webproxyservers.yml

- include: common.yml

- include: java.yml

- include: tomcat.yml

- include: postgresql.yml

- include: deploy.yml
