---

- name: Update package cache (Debian)
  apt: update_cache=yes cache_valid_time=86400
  become: yes

- name: Ensure Tomcat is installed (Debian)
  apt: name=tomcat{{ tomcat_version }} state=present
  become: yes
