---
# Either 7 or 8
tomcat_version: "8"
#tomcat_java_home: "/usr/lib/jvm/java-7-openjdk"
#tomcat_java_opts: "-Djava.awt.headless=true -Xmx128m -XX:+UseConcMarkSweepGC"
# faster startup
tomcat_java_opts: "-Djava.awt.headless=true -Xmx128m -XX:+UseConcMarkSweepGC -Djava.security.egd=file:/dev/./urandom"

tomcat_java_home: "/usr/lib/jvm/java-8-oracle/jre"

tomcat_connectors:
  - port: "8080"
    protocol: "HTTP/1.1"
    connection_timeout: "20000"
    #executor: "tomcatThreadPool"
    #proxy_port: "443"
    redirect_port: "8443"
    #scheme: "https"
    uri_encoding: "UTF-8"
